spring:
  application:
    name: Cloud-service
  redis:
    host: 192.168.1.111
    port: 6379
    database: 0

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



